title: mantrue - 承鹏辉博客- 承鹏辉
name: mantrue
email: penghui219@163.com
description: 承鹏辉，网名mantrue，PHP工程师，从事web相关的开发工作。开源爱好者，GitHub:https://github.com/mantrue。
keywords: 承鹏辉，承鹏辉博客，承鹏辉个人博客，承鹏辉技术交流
skill_keywords: [PHP, Javascript, HTML+CSS, Linux, RESTful, Sublime Text]

timezone:    PRC
encoding: "utf-8"

url: http://mantrue.github.io
baseurl:  "/"
domain:    mantrue.github.io
permalink:     /articles/:year/:month/:title.html
paginate_path: 'page:num'
paginate:   10
source_code: https://github.com/mantrue/mantrue.github.io

# Build settings
markdown:    kramdown
highlighter: pygments
lsi:         false
excerpt_separator: "\n\n"

source:      .
destination: ./_site

quiet:    false
defaults: []

kramdown:
  input: GFM
  enable_coderay: true

gems:
  - jemoji
  - rouge
  # # # - jekyll-mentions
  # - jekyll-sitemap
  - jekyll-html-pipeline

disqus:
  id: mantrue

google:
    analytics_id: UA-55452630-1

# navigation
navs:
  -
    href: /
    label: Home

  -
    href: /open-source
    label: Open-Source

  -
    href: https://github.com/mantrue
    label: GitHub
    target: _blank

  -
    href: http://weibo.com/peen219
    label: Weibo
    target: _blank

  -
    href: /bookmark
    label: Bookmark

  -
    href: /about
    label: About

popular_repos: ['Grab']
contribute_repos: ['laravel/framework', 'top-think/thinkphp']